name: Sync from Codeberg
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at 00:00 UTC
  workflow_dispatch:  # Allows manual trigger
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: master
    - name: Fetch from Codeberg
      run: |
        git remote set-url codeberg https://codeberg.org/timelimit/timelimit-server.git
        git fetch codeberg
        git pull codeberg master --allow-unrelated-histories
    - name: Push to GitHub
      run: |
        git push origin master
