name: Sync from Codeberg
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at 00:00 UTC
  workflow_dispatch:  # Allows manual trigger
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch from Codeberg
      run: |
        git remote add codeberg https://codeberg.org/timelimit/timelimit-server.git || true
        git fetch codeberg
        git merge codeberg/master --allow-unrelated-histories
    - name: Push to GitHub
      run: |
        git push origin master
